/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: "0lzAQNRW0JA",
    name: "Yeh jawaani hai deeewani",
    actors: ["Ranbir Kapoor", "Deepika Padukone"],
    releaseYear: 2013,
    category: "Drama",
    language: "Hindi",
    duration: { hours: 2, minutes: 40 },
    views: 53657899,
    startAt: 70,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648831994/video%20library/video-thumbnails/LmpwZw_rc9uac.jpg",
  },
  {
    _id: "dW1oSXK61k4",
    name: "Parasite",
    actors: ["Bong Joon-ho", "Song Kang-ho"],
    category: "Drama",
    language: "Korean",
    releaseYear: 2019,
    duration: { hours: 2, minutes: 12 },
    views: 23757801,
    startAt: 58,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648306157/video%20library/video-thumbnails/SyZwaWQ9QXBp_otdmzy.jpg",
  },
  {
    _id: "pzNHnzupGSs",
    name: "3 Idiots",
    actors: ["Aamir Khan", "Kareena Kapoor"],
    category: "Comedy",
    language: "Hindi",
    releaseYear: 2009,
    duration: { hours: 2, minutes: 50 },
    views: 93757801,
    startAt: 60,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648312196/video%20library/video-thumbnails/TCZwaWQ9QXBp_ing9wp.jpg",
  },
  {
    _id: "bXZGGNOa2AQ",
    name: "Qismat 2",
    actors: ["Ammy Virk", "Sara Gurpal"],
    releaseYear: 2019,
    category: "Romance",
    language: "Punjabi",
    duration: { hours: 2, minutes: 30 },
    startAt: 60,
    views: 16257899,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648294974/video%20library/video-thumbnails/ems_acp9dc.jpg",
  },
  {
    _id: "S8ZUtWTuHT4",
    name: "Spider-Man: No Way Home",
    actors: ["Tom Holland", "Zendaya"],
    releaseYear: 2021,
    category: "Action",
    language: "English",
    duration: { hours: 2, minutes: 28 },
    views: 82657899,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648307999/video%20library/video-thumbnails/p19651051_k_h9_ac_btuz2d.jpg",
  },
  {
    _id: "slYoTyn2GUs",
    name: "Sufna",
    actors: ["Ammy Virk", "Tania"],
    releaseYear: 2020,
    category: "Romance",
    language: "Punjabi",
    duration: { hours: 2, minutes: 24 },
    views: 13657899,
    startAt: 60,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648824110/video%20library/video-thumbnails/ab67616d00001e02bf362b4ff7b1ad0c1c083b6c_xbuqtb.jpg",
  },
  {
    _id: "ULEQb_l-N08",
    name: "K.G.F: The Movie",
    actors: ["Yash", "Srinidhi Shetty"],
    releaseYear: 2018,
    category: "Action",
    language: "Kannada",
    duration: { hours: 2, minutes: 47 },
    views: 13657899,
    startAt: 41,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648308523/video%20library/video-thumbnails/Ml8xNDI0MTEuanBn_k1et2r.jpg",
  },
  {
    _id: "7obSU9DX2dY",
    name: "The Dog",
    actors: ["Channing Tannum", "Jane Adams"],
    releaseYear: 2022,
    category: "Comedy",
    language: "English",
    duration: { hours: 1, minutes: 41 },
    views: 12757801,
    startAt: 55,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648295082/video%20library/video-thumbnails/ems_zx6tpw.jpg",
  },
  {
    _id: "TIQ5hrfermg",
    name: "Hera Pheri",
    actors: ["Akshay Kumar", "Paresh Rawal"],
    releaseYear: 2000,
    category: "Comedy",
    language: "Hindi",
    duration: { hours: 2, minutes: 18 },
    views: 210357801,
    startAt: 29,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648478417/video%20library/video-thumbnails/MV5BMzBhNWZjNTctY2UwMy00NmQzLWIyMDktM2IzODQ3ZDAwZmFkXkEyXkFqcGdeQXVyODMyODMxNDY_._V1_FMjpg_UX1280__tqnkuh.jpg",
  },
  {
    _id: "5YSVUxk4v6I",
    name: "The Transporter 3",
    actors: ["Jason Statham", "Robert Knapper"],
    releaseYear: 2008,
    category: "Action",
    language: "English",
    duration: { hours: 1, minutes: 44 },
    views: 146457801,
    startAt: 20,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648482365/video%20library/video-thumbnails/MV5BMGNmNGI5MTctY2ExZC00ZTY4LTljMTAtZTQwZjU0YmVjODc4XkEyXkFqcGdeQXVyOTc5MDI5NjE_._V1_FMjpg_UX1280__bmlugy.jpg",
  },
  {
    _id: "mrP2eK_xHcg",
    name: "Punjab 1984",
    actors: ["Diljit Dosanjh", "Kirron Kher"],
    releaseYear: 2014,
    category: "History",
    language: "Punjabi",
    duration: { hours: 2, minutes: 39 },
    views: 9457801,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648298497/video%20library/video-thumbnails/LmpwZw_wc6y9e.jpg",
  },
  {
    _id: "NuYC3J9jobw",
    name: "Black Panther",
    actors: ["Chadwick Boseman", "Michael B. Jordan"],
    releaseYear: 2018,
    category: "Adventure",
    language: "English",
    duration: { hours: 2, minutes: 14 },
    views: 718457801,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648296502/video%20library/video-thumbnails/anBlZz9zc2w9MQ_ssksy3.jpg",
  },
  {
    _id: "vB2m1uRF30c",
    name: "Sooryavansham",
    actors: ["Amitabh Bachan", "Soundarya"],
    releaseYear: 1999,
    category: "Drama",
    language: "Hindi",
    duration: { hours: 3, minutes: 24 },
    views: 270457801,
    startAt: 70,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648964432/video%20library/video-thumbnails/hqdefault_nefk8o.webp",
  },
  {
    _id: "neB7WugMKT4",
    name: "2 States",
    actors: ["Arjun Kapoor", "Alia Bhatt"],
    releaseYear: 2014,
    category: "Romance",
    language: "Hindi",
    duration: { hours: 2, minutes: 29 },
    views: 27457801,
    startAt: 54,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648964935/video%20library/video-thumbnails/MV5BMDdhNjRmNjYtOTFjNC00MDM0LWJhNDItMGRmNDFmN2ZmZTEzXkEyXkFqcGdeQXVyNjkwOTg4MTA_._V1_FMjpg_UX1000__tsh8ey.jpg",
  },
  {
    _id: "zBXa6Foq9ZM",
    name: "Bang Bang",
    actors: ["Hrithik Roshan", "Katrina Kaif"],
    releaseYear: 2014,
    category: "Action",
    language: "Hindi",
    duration: { hours: 2, minutes: 16 },
    views: 13757801,
    startAt: 87,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648966533/video%20library/video-thumbnails/MV5BM2IzNGRiNTAtZDIzMi00ZGMxLWExOWMtMzc5YThiMzVjMTZiXkEyXkFqcGdeQXVyNjE1OTQ0NjA_._V1_FMjpg_UX535__plqnlk.jpg",
  },
  {
    _id: "odrWtmqVYsE",
    name: "Bajirao Mastani",
    actors: ["Ranveer Singh", "Deepika Padukone"],
    releaseYear: 2015,
    category: "History",
    language: "Hindi",
    duration: { hours: 2, minutes: 38 },
    views: 7757801,
    startAt: 185,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648967312/video%20library/video-thumbnails/MV5BYmU3MmE3NDItYWQxYS00NDEzLWI2NTktMjNkNjVlMDViZjE2XkEyXkFqcGdeQXVyOTc5MDI5NjE_._V1_FMjpg_UX1280__igeurq.jpg",
  },
  {
    _id: "oD-QraSGTso",
    name: "Jolly LLB 2",
    actors: ["Akshay Kumar", "Huma Qureshi"],
    releaseYear: 2017,
    category: "Comedy",
    language: "Hindi",
    duration: { hours: 2, minutes: 0 },
    views: 7757801,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648967989/video%20library/video-thumbnails/MV5BMTdiMDlkNWQtYWU3Mi00ZmU1LWE3OTQtZDEyMWY3ZWNkM2ZjXkEyXkFqcGdeQXVyNjkyODM4NDg_._V1_FMjpg_UX640__shcb6h.jpg",
  },
  {
    _id: "_fRsCnEP7E4",
    name: "ABCD",
    actors: ["Prabhu Deva", "Ganesh Acharya"],
    releaseYear: 2013,
    category: "Drama",
    language: "Hindi",
    duration: { hours: 1, minutes: 30 },
    views: 2407801,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648969156/video%20library/video-thumbnails/MV5BMTM2OTY3MDU4MF5BMl5BanBnXkFtZTcwMzg2MzU1Nw_._V1_FMjpg_UX1280__viplrm.jpg",
  },
  {
    _id: "H-ocPpO3iwM",
    name: "Rowdy Rathore",
    actors: ["Akshay Kumar", "Sonakshi Sinha"],
    releaseYear: 2013,
    category: "Romance",
    language: "Hindi",
    duration: { hours: 1, minutes: 56 },
    views: 1107801,
    thumbnail:
      "https://res.cloudinary.com/furnhouse/image/upload/v1648969583/video%20library/video-thumbnails/hqdefault_erujjc.webp",
  },
];
